from enum import Enum


class ConversationState(Enum):
    GREETING = "GREETING"
    WAITING_FOR_RECEIPT = "WAITING_FOR_RECEIPT"
    RECEIPT_PROCESSING = "RECEIPT_PROCESSING"
    VALIDATION = "VALIDATION"
    CLARIFICATION = "CLARIFICATION"
    COMPLETED = "COMPLETED"
    FOLLOW_UP = "FOLLOW_UP"
